name: Terraform Plan

on:
  pull_request:
    branches: [ master ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      ARM_CLIENT_ID: 86a6c589-9c44-4746-ae18-68b49f7ac919
      ARM_CLIENT_SECRET: ${{secrets.TF_ARM_CLIENT_SECRET}}
      ARM_SUBSCRIPTION_ID: f03ec79e-f8b1-4b74-8883-0f5ac526537f
      ARM_TENANT_ID: e2f31894-997e-4df7-8e8f-66324c7dea5c

    steps:
      - uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init


      - name: Terraform Plan
        run: terraform plan
